name: Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      os: [ubuntu-latest]
      python-version: ['3.9']

    steps:
      - uses: actions/checkout@v2
      - name : Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Add Poetry Dependencies to requirements.txt File
        run: poetry export --dev -f requirements.txt --output requirements.txt
      - name: Install Dependencies
        run: pip install -r requirements.txt
      