name: Lint, Type Check and Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

  setup-poetry:
    runs-on: ubuntu-latest
    needs: setup-python
    steps:
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install Dependencies
        run: make install

  lint-and-type-check:
    runs-on: ubuntu-latest
    needs: setup-poetry
    steps:
      - name: Lint
        run: make lint
      - name: Type Check
        run: make type_check

  run-tests:
    runs-on: ubuntu-latest
    needs: lint-and-type-check
    steps:
      - name: Run Tests
        run: make test